Update Kernel (#85)
* Update Kernel

改为基于OpenWRT25.12.1开发，使用apk进行包管理，并基于Kernel6.12.71

Signed-off-by: fwerkor <3116935098@qq.com>

* 进一步完善更新流程

Signed-off-by: fwerkor <3116935098@qq.com>

---------

Signed-off-by: fwerkor <3116935098@qq.com>

diff --git a/feeds/packages/net/kea/files/kea.init b/feeds/packages/net/kea/files/kea.init
--- a/feeds/packages/net/kea/files/kea.init
+++ b/feeds/packages/net/kea/files/kea.init
@@ -8,8 +8,7 @@ BIN_PATH="/usr/sbin"
 CONF_PATH="/etc/kea"
 
 start_service() {
-	mkdir -p /var/run/kea /var/lib/kea
-    chmod 0750 /var/run/kea /var/lib/kea
+	mkdir -p /var/run/kea
 
 	config_load "kea"
 	config_foreach start_kea "service"
@@ -30,7 +29,9 @@ start_kea() {
 			cnf="${CONF_PATH}/kea-${name}.conf"
 			;;
 		*)
-			return 0
+			echo "Error: Invalid service name '$name'" >&2
+			return 1
+			;;
 	esac
 
 	procd_open_instance "$name"
